[package]
name = "flags-api"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
flags-core.workspace = true
otto-tenant.workspace = true
otto-resource.workspace = true
serde.workspace = true
serde_json.workspace = true
chrono.workspace = true
uuid.workspace = true
tracing.workspace = true
axum.workspace = true
http.workspace = true
tokio.workspace = true
tokio-stream.workspace = true
futures.workspace = true
tower-http.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["full"] }
tower = { workspace = true, features = ["util"] }
